#pragma once

#include <filesystem>

class c_config final {
public:
	void run(const char*) noexcept;
	void load(size_t) noexcept;
	void save(size_t) const noexcept;
	void add(const char*) noexcept;
	void remove(size_t) noexcept;
	void rename(size_t, const char*) noexcept;
	void reset() noexcept;

	constexpr auto& get_configs() noexcept {
		return configs;
	}

	struct {
		bool backtrack{ true };
		bool backtrack_chams{ false };
		bool aim_enabled{ false };
		bool scope_aim{ true };
		bool smoke_check{ false };
		bool aim_silent{ false };
		bool aim_distance_based_fov{ true };
		float aim_fov_pistol{ 3.0f };
		float rcs_x_pistol{ 0.0f };
		float rcs_y_pistol{ 0.0f };
		float rcs_x_rifle{ 0.4f };
		float rcs_y_rifle{ 0.4f };
		float rcs_x_sniper{ 0.0f };
		float rcs_y_sniper{ 0.0f };
		float rcs_x_heavy{ 0.0f };
		float rcs_y_heavy{ 0.0f };
		float rcs_x_smg{ 0.0f };
		float rcs_y_smg{ 0.0f };
		bool dropped_weapons_icon{ false };
		float aim_smooth_pistol{ 2.f };
		float clr_weapon_chams[4]{153 /255.f,100/255.f,0/255.f,255.0f };
		float clr_hand_chams[4]{ 175 / 255.f, 201 / 255.f, 22 / 255.f, 1.0f };
		float clr_weapon_drop[4]{ 255 / 255.f, 255 / 255.f, 255 / 255.f, 1.0f };
		float clr_sleeve_chams[4]{ 175 / 255.f, 201 / 255.f, 22 / 255.f, 1.0f };
		bool sleeve_chams{ false };
		bool hand_chams{ false };
		float aim_fov_rifle{ 2.0f };
		float aim_smooth_rifle{ 3.f };
		float aim_fov_sniper{ 1.0f };
		float aim_smooth_sniper{ 8.f };
		float aim_fov_heavy{ 1.0f };
		float aim_smooth_heavy{ 1.f };
		float aim_fov_smg{ 1.0f };
		float aim_smooth_smg{ 5.f };
		int aim_bone_smg{ 0 };
		int aim_bone_sniper{ 0 };
		bool weapon_chams{ false };
		int aim_bone_pistol{ 0 };
		int aim_mode{ 0 };
		int aim_bone_rifle{ 0 };
		int aim_bone_heavy{ 0 };
		int aim_weapon{ 0 };;
		bool aim_team_check{ false };
		bool bomb_planted{ false };
		bool dropped_weapons{ false };
		bool backtrack_skeleton{ false };
		bool visuals_preview{ false };
		bool sound_footstep{ true };
		bool skeleton{ false };
		bool danger_zone_dropped{ false };
		bool visuals_enabled{ false };
		bool anti_screenshot{ false };
		bool remove_smoke{ false };					
		bool visuals_glow{ false };
		bool visuals_glow_enemy{ false };
		bool visuals_glow_team{ false };
		bool visuals_glow_planted{ false };
		bool visuals_glow_weapons{ false };
		bool player_name{ false };
		bool player_dormant{ false };
		bool player_ammo{ false };
		bool player_flags{ true };
		bool player_flags_armor{ true };
		bool player_flags_money{ false };
		bool player_flags_scoped{ false };
		bool player_flags_c4{ true };
		bool player_flags_flashed{ true };
		int player_box{ 1 };
		bool player_box1{ false };
		bool player_health{ true };
		bool player_weapon{ true };
		bool player_armor{ true };
		float clr_chams_vis[4]{ 1.0f,1.0f,1.0f,1.0f };
		float clr_chams_invis[4]{ 1.0f,1.0f,1.0f,1.0f };
		float clr_glow[4]{255 /255.f,102/255.f,255/255.f,0.7f };
		float clr_glow_team[4]{ 1.0f,1.0f,1.0f,1.0f };
		float clr_glow_planted[4]{ 1.0f,1.0f,1.0f,1.0f };
		float clr_glow_dropped[4]{ 1.0f,1.0f,1.0f,1.0f };
		float clr_sky[4]{ 1.0f,1.0f,1.0f,1.0f };
		float clr_box[4]{ 146 / 255.f, 97 / 255.f, 201 / 255.f, 255 / 255.f };
		bool relay_cluster{ false };
		float clr_name[4]{149 / 255.f,0/255.f,255/255.f,1.0f }; 
		float clr_weapon[4]{ 1.0f,1.0f,1.0f,1.0f };
		float clr_footstep[4]{ 1.0f,1.0f,1.0f,1.0f };
		bool chams{ false };
		bool remove_scope{ false };
		int vis_chams_type{ 0 };
		int relay_cluster_select{ 0 };
		int vis_chams_type1{ 0 };
		int viewmodel_fov{ 0 };
		int viewmodel_x{ 0 };
		int viewmodel_y{ 0 };
		int viewmodel_z{ 0 };
		int knife_wear{ 0 };
		int fov{ 0 };
		int nightmode_brightness{ 100 };
		bool reduce_flash{ false };
		bool remove_sleeves{ false };
		bool remove_hands{ false };
		bool entity_esp{ false };
		bool projectiles{ false };
		float flash_alpha{ 255.f };
		bool force_crosshair{ false };
		bool visuals_team_check{ false };
		bool vis_chams_vis{ false };
		bool vis_chams_invis{ false };
		bool nightmode{ false };
		bool spectators_list{ true };
		bool watermark{ false };
		bool misc_enabled{ false };
		bool misc_save_config{ false };
		bool misc_load_config{ false };
		bool bunny_hop{ false };
		bool bunny_hop_humanize{ false };
		bool bunny_hop_minimum{ false };
		bool bunny_hop_maximum{ false };
		int bunny_hop_minimum_value{ 0 };
		int bunny_hop_maximum_value{ 0 };
		int bunny_hop_hitchance{ 0 };
		bool clan_tag{ false };
		bool radar{ false };
		bool hitmarker{ false };
		bool viewmodel_offset{ false };
		bool logs_player_hurt{ false };
		bool logs_player_bought{ false };
		bool logs_config_system{ false };
		bool skinchanger_enable{ true };
		int hitmarker_sound{ 1 };
		int knife_model{ 2 };
		int knife_skin{ 0 };
		int config_selection{ 0 };
		int keybinds_selection{ 0 };
		bool visibletog1 = false;
		bool trigger_enable = true;
		bool trigger_hitbox_head = true;
		bool trigger_hitbox_body = true;
		bool trigger_hitbox_arms = true;
		bool trigger_hitbox_legs = false;
		int trigger_delay = 2;
		int trigger_key = 16;
		
		
		
		float free_cam_speed = 0;
		bool free_cam = false;
		bool chat_spam = false;
		bool walk_bot = false;
		float walk_bot_distance = 0;
		int walk_bot_turn = 0;
		bool ragdoll_gravity = false;
		bool fake_ping = false;
		int fake_ping_value = 0;
		bool is_defusing = false;
		bool draw_enemy_sight = false;
		float clr_bullet_beams[4] = { 1.0f,1.0f,1.0f,1.0f };
		bool bullet_beams = false;
		int bullet_beams_width = 0;
		int bullet_beams_duration = 0;
		bool aim_auto_fire = false;
		float clr_world_color[4] = { 1.0f,1.0f,1.0f,1.0f };
		bool world_color = false;
		bool aim_auto_stop = false;

		
		
		bool nade_pred = true;
		bool fake_lag_enable = false;
		int fake_lag_type = 1;
		int fake_lag_amount = 4;
		bool fake_duck = false;
		bool desync = false;
		float desync_range = 0;
		bool rage_enable = false;
		bool thirdperson_spectators = false;
		bool fake_walk = true;
		int fake_walk_key = 4;
		bool visibletog2 = true;
		
		bool edge_jump_duck_in_air{ false };
		int edge_jump_key{ 0 };
		int changer_skin{1 };
		int paint_kit_vector_index_knife{ 0 };
		int paint_kit_index_knife{ 0 }; //409
		int paint_kit_vector_index_usp{ 0 };
		int paint_kit_index_usp{ 504 };
		int paint_kit_vector_index_p2000{ 0 };
		int paint_kit_index_p2000{ 184 };
		int paint_kit_vector_index_glock{ 0 };
		int paint_kit_index_glock{ 38 };
		int paint_kit_vector_index_p250{ 0 };
		int paint_kit_index_p250{ 388 };
		int paint_kit_vector_index_fiveseven{ 0 };
		int paint_kit_index_fiveseven{ 660 };
		int paint_kit_vector_index_tec{ 0 };
		int paint_kit_index_tec{ 0 };
		int paint_kit_vector_index_cz{ 0 };
		int paint_kit_index_cz{ 0 };
		int paint_kit_vector_index_duals{ 0 };
		int paint_kit_index_duals{ 0 };
		int paint_kit_vector_index_deagle{ 0 };
		int paint_kit_index_deagle{ 37 };
		int paint_kit_vector_index_revolver{ 0 };
		int paint_kit_index_revolver{ 0 };
		int paint_kit_vector_index_famas{ 0 };
		int paint_kit_index_famas{ 0 };
		int paint_kit_vector_index_galil{ 0 };
		int paint_kit_index_galil{ 0 };
		int paint_kit_vector_index_m4a4{ 0 };
		int paint_kit_index_m4a4{ 695 };
		int paint_kit_vector_index_m4a1{ 0 };
		int paint_kit_index_m4a1{ 0 };
		int paint_kit_vector_index_ak47{ 0 };
		int paint_kit_index_ak47{ 282 };
		int paint_kit_vector_index_sg553{ 0 };
		int paint_kit_index_sg553{ 0 };
		int paint_kit_vector_index_aug{ 0 };
		int paint_kit_index_aug{ 0 };
		int paint_kit_vector_index_ssg08{ 0 };
		int paint_kit_index_ssg08{ 624 };
		int paint_kit_vector_index_awp{ 0 };
		int paint_kit_index_awp{ 838 };
		int paint_kit_vector_index_scar{ 0 };
		int paint_kit_index_scar{ 0 };
		int paint_kit_vector_index_g3sg1{ 0 };
		int paint_kit_index_g3sg1{ 0 };
		int paint_kit_vector_index_mac10{ 0 };
		int paint_kit_index_mac10{ 665 };
		int paint_kit_vector_index_mp5sd{ 0 };
		int paint_kit_index_mp5sd{ 0 };
		int paint_kit_vector_index_mp7{ 0 };
		int paint_kit_index_mp7{ 752 };
		int paint_kit_vector_index_mp9{ 0 };
		int paint_kit_index_mp9{ 0 };
		int paint_kit_vector_index_ppbizon{ 0 };
		int paint_kit_index_ppbizon{ 0 };
		int paint_kit_vector_index_p90{ 0 };
		int paint_kit_index_p90{ 0 };
		int paint_kit_vector_index_ump45{ 0 };
		int paint_kit_index_ump45{ 0 };
		int paint_kit_vector_index_mag7{ 0 };
		int paint_kit_index_mag7{ 0 };
		int paint_kit_vector_index_nova{ 0 };
		int paint_kit_index_nova{ 0 };
		int paint_kit_vector_index_sawedoff{ 0 };
		int paint_kit_index_sawedoff{ 0 };
		int paint_kit_vector_index_xm1014{ 0 };
		int paint_kit_index_xm1014{ 0 };
		int paint_kit_vector_index_m249{ 0 };
		int paint_kit_index_m249{ 0 };
		int paint_kit_vector_index_negev{ 0 };
		int paint_kit_index_negev{ 0 };
		bool aimbot_enable = true;
		int aimbot_fov = 3;
		int aimbot_smooth = 2;
		
		float backtrack_ms{ 200.0f };
		int aim_key{ 0 };
		bool backtrack_visualize{ false };
		bool vis_chams_smoke_check{ true };
		bool disable_post_processing{ false };
		bool recoil_crosshair{ false };
		bool rank_reveal{ true };
		bool vis_chams_vis_teammate{ false };
		bool vis_chams_invis_teammate{ false };
		float clr_chams_vis_teammate[4]{ 1.0f,1.0f,1.0f,1.0f };
		float clr_logs[4]{ 146 / 255.f, 97 / 255.f, 201 / 255.f, 255 / 255.f };
		float clr_crosshair[4]{ 255 / 255.f, 255 / 255.f, 255 / 255.f, 255 / 255.f };
		float clr_chams_invis_teammate[4]{ 1.0f,1.0f,1.0f,1.0f };
		int aimbot_delay_after_kill{ 0 };
		bool aimbot_auto_pistol{ false };
		bool visuals_visible_only{ false };
		bool visuals_on_key{ false };
		int visuals_key{ 0 };
		bool crosshair_color{ false };
		bool crosshair_outline_color{ false };
		
		float clr_theme[4]{ 146 / 255.f, 97 / 255.f, 201 / 255.f, 255 / 255.f };
		float clr_crosshair_outline[4]{ 1.0f,1.0f,1.0f,1.0f };
		bool glovechanger_enable{ false };
		int glove_model{ 4 };
		int glove_skin{ 0 };
		int paint_kit_vector_index_glove{ 0 };
		int paint_kit_index_glove{ 10021 };
		int glove_wear{ 0 };
		float rcs_standalone_x{ 0.0f };
		float rcs_standalone_y{ 0.0f };
		bool aim_jump_check{ false };
		bool viewmodeltoggle{ false };
		bool anti_aim = false;
		bool d3d = false;
		bool anti_aim_yaw= false;
		bool anti_aim_pitch = false; 
			bool weaponchamerino = false;
			bool tonyhawk = false;
			bool ragdoll = false;
			bool yaw_flip = true;
			bool rainbow_theme = false;
			bool rcs_standalone = false;
			bool additional_info = false;
			float yaw = 0.0f;
			float pitch = 0.0f;
			int packets = 0;
			bool third_person{ false };
			int third_person_key = 4;
			bool offscreen{ false };
	} item;

private:
	std::filesystem::path path;
	std::vector<std::string> configs;
};

extern c_config config_system;
